### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Jisans** [fermi-lat/Fermitools-conda#126]
Hello all,

I use `conda create -n fermi -c conda-forge -c fermi fermitools python=3` success  Installation fermitools 

When `You have LD_LIBRARY_PATH set. This might interfere with the correct functioning of conda and the Fermitools.`
`You have PYTHONPATH set. This might interfere with the correct functioning of conda and the Fermitools. `appears after I use conda to activate the environment, how can I solve this problem

System:Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
conda env
Python 3.9.13, pip 22.2.2,fermitools 2.2.0

**Comment by donhorner** [comment]
Those are just warnings.  If you encounter any problems,  you might want to unset them.  That usually only occurs if something else has conflicting libraries installed, and one of those paths is putting the wrong version first from the Fermitools perspective. You might later see a warning about different CFITSIO versions, but that is also not a problem.  It's just because a dependency like astropy has it's own version of the library.   Generally, unless the Fermitools don't work these types of warnings can be ignored.
