### ISSUE TITLE
Error installing threeml, fermitools, fermipy using conda

### ISSUE THREAD

**Issue by Jisans** [fermi-lat/Fermitools-conda#127]
Hell all,
I am trying to install fermitools, fermipy and threeml in the same environment using conda. I created a virtual environment using conda create -- name fermi3ML - c conda forge - c fermi - c threeml. I continue to use conda install - c conda forge - c xspecmodels xspec models only, conda install - c conda forge - c threeml - c fermi threeml fermipy fermitools.It is strange that I can use fermitools, threeml and fermipy in ipython. I tried to import threeml in jupyter lab, but there was such a warning,I don't know where the problem is. Can you help me? thank you!
#Note:System:Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 https://github.com/fermi-lat/Fermitools-conda/pull/1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
conda env
Python 3.9.13, pip 22.2.2,fermitools 2.2.0,fermipy 1.0.1,fermitools-data 0.18,threeml 2.3.2

![image](https://user-images.githubusercontent.com/110452095/187142874-58434eb6-bbd1-447e-b51e-f5ffe2412844.png)

**Comment by Areustle** [comment]
We cannot help you with threeml errors, nor with jupyterlab errors. Please contact the support team of threeml for assistance.

**Comment by Jisans** [comment]
Hello, sir, I found a common problem. I remember that I ran from fermipy in jupyter lab Gtanalysis import gtanalysis, the same situation will occur
[/fermiPy/fermipy/issues/487](url)

**Comment by Areustle** [comment]
Fermipy is a separate, community project. 

Please communicate issues you encounter with fermipy to https://github.com/fermiPy
Rather than the official fermitools issue tracker.

**Comment by Jisans** [comment]
@Areustle 
 Sir, There is the same problem here,

[Notebooks kernel died ! #487](https://github.com/fermiPy/fermipy/issues/487)
[Module installation #476](https://github.com/fermiPy/fermipy/issues/476)

**Comment by nmirabal** [comment]
Closing. This has been posted in fermipy issues
https://github.com/fermiPy/fermipy/issues/498

**Comment by donhorner** [comment]
I think the only issue that might be related to the Fermitools here is that you have to run the `conda install nb_conda` to use Jupyter notebooks with the tools (see [Additional Software](https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions#additional-software) section). Otherwise, the notebook might be pick up a different python installation. 

The Fermitools+fermipy+3ML combo seems to work fine in the [FermiBottle ](https://github.com/fermi-lat/FermiBottle/wiki) Docker container although I get a bunch of warnings about packages like naima not being installed.  I also installed fermipy and 3ML in my Fermitools environment on my Mac and the 3ML import worked (with the same warnings).

**Comment by Jisans** [comment]
@donhorner  I'll try. If I make a mistake, I'll ask you again. Thank you!
