### ISSUE TITLE
lightcurve query

### ISSUE THREAD

**Issue by Fredtrotteville** [fermi-lat/Fermitools-conda#30]
It is mentioned in the official fermi tutorial for generating lightcurves
https://fermi.gsfc.nasa.gov/ssc/data/p7rep/analysis/scitools/python_tutorial.html

that all the parameters except 'Index' and 'Integral' should be fixed . I am not sure as to what are the consequences of having all the parameters fixed as opposed to having the said two parameters freed. Also, what is the reasoning behind freeing the 'Index' and 'Integral' only? What if all the parameters were freed. It would be a great help if anyone could please explain or perhaps direct me towards a tutorial with detailed explanations.

Thanks in advance.

**Comment by nmirabal** [comment]
That is a very old tutorial and no longer up to date. In fact, you can leave all parameters of the source of interest free if you like. Note that the parameter names have changed since then. For a power law, the parameters are called Prefactor, index and scale. You can read what each means in the following link

https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/source_models.html

One recommendation is to freeze all the parameters for the remaining sources in the XML file.
