### ISSUE TITLE
Caught St13runtime_error at the top level: RoiCuts::sortCuts: 

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Fermitools-conda#40]
What does the error mean?

**Comment by donhorner** [comment]
This error occurs when a tool such as gtexpmap finds duplicate DSS keywords in the FITS header, so you must delete one of the duplicated keywords. After that you must change the keyword NDSKEYS to reflect the surviving number of DSS keywords. You also must renumber the remaining keywords so that the numbering is consecutive and the max is the same as the total number, otherwise the tool will fail. You can use the FTOOL fv to accomplish this, but other FTOOLS such as fmodhead or fparkey should also work.

To avoid this error, when using gtselect be certain to match the following parameters to the exact values used when extracting the data from the LAT data server:
 *    Minimum and maximum event energies
 *   RA and DEC positions for the acceptance cone
 *   Tmin and Tmax in MET

**Comment by Sanjuphysics12** [comment]
@donhorner, when I was using 'gtselect', I put the exact values of emin, emax, tmin, tmax , ra and dec. Even I checked several times even after putting those values accurately I got the error.

**Comment by nmirabal** [comment]
Please download the files again. Step by step guides for binned and unbinned analyses are provided at:
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/likelihood_tutorial.html
