### ISSUE TITLE
Change of key name Spectral_Index in gll_psc_v19.fit

### ISSUE THREAD

**Issue by Fredtrotteville** [fermi-lat/Fermitools-conda#73]
In previous versions of Fermi catalog like gll_psc_v16 there used to be a key "Spectral_Index". But in recent versions v19 I cannot access it as before in NAXIS2 as before. Can anyone please tell me how to access it. Thanks for the help in advance.

**Comment by jballet** [comment]
Yes, that is correct. Between 3FGL and 4FGL we deleted the column Spectral_Index because it was ambiguous (it had a different meaning depending on SpectrumType).
There are now different columns for each spectral model (PowerLaw, LogParabola and PLSuperExpCutoff), called PL_Index (same as PowerLaw_Index in 3FGL, but renamed for consistency with new column names), LP_Index and PLEC_Index. Each source has a full set of parameters for all spectral models. 
The detailed description is in Table 12 of the [4FGL paper](https://ui.adsabs.harvard.edu/abs/2020ApJS..247...33A/abstract) and the rationale is explained at the end of Sect 3.3.
If you absolutely want to recover what was in Spectral_Index (I would discourage that), the logic is
case SpectrumType of
PowerLaw: Spectral_Index = PL_Index
LogParabola: Spectral_Index = LP_Index
PLSuperExpCutoff: Spectral_Index = PLEC_Index

**Comment by Fredtrotteville** [comment]
Thanks for the explanation. This helped a lot.
